# Generated by Django 6.0.6 on 2026-08-10 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('APP_OPEN', 'App Open'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VEHICLE_CREATED', 'Vehicle Created'), ('BOOKING_CREATED', 'Booking Created'), ('BOOKING_COMPLETED', 'Booking Completed'), ('ORDER_CREATED', 'Order Created'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PRODUCT_VIEWED', 'Product Viewed'), ('NEWS_VIEWED', 'News Viewed'), ('AD_CLICKED', 'Advertisement Clicked'), ('SERVICE_VIEWED', 'Service Viewed')], db_index=True, max_length=50)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_c3dcde_idx'), models.Index(fields=['user', 'created_at'], name='analytics_e_user_id_7e4ee5_idx')],
            },
        ),
    ]
