# Generated by Django 6.0.6 on 2026-08-10 23:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('geofence_type', models.CharField(choices=[('CIRCLE', 'Circle')], default='CIRCLE', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('radius_meters', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notify_on_enter', models.BooleanField(default=True)),
                ('notify_on_exit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'geofences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENTER', 'Enter'), ('EXIT', 'Exit')], max_length=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.geofence')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'geofence_events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MechanicLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('speed_kmh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('heading', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('is_online', models.BooleanField(db_index=True, default=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mechanic_locations',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('tracking_type', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('MECHANIC', 'Mechanic'), ('BOOKING', 'Booking'), ('DELIVERY', 'Delivery')], db_index=True, default='VEHICLE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_location_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_distance_km', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'tracking_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('speed_kmh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('heading', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('source', models.CharField(choices=[('GPS', 'GPS'), ('NETWORK', 'Network'), ('MANUAL', 'Manual'), ('BLUETOOTH', 'Bluetooth'), ('OBD', 'OBD')], default='GPS', max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tracking.trackingsession')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_locations',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['user', 'is_active'], name='geofences_user_id_f80793_idx'),
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['vehicle', 'is_active'], name='geofences_vehicle_d547ec_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['geofence', 'occurred_at'], name='geofence_ev_geofenc_a8e08f_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['vehicle', 'occurred_at'], name='geofence_ev_vehicle_3380cd_idx'),
        ),
        migrations.AddIndex(
            model_name='mechaniclocation',
            index=models.Index(fields=['mechanic', 'recorded_at'], name='mechanic_lo_mechani_44a390_idx'),
        ),
        migrations.AddIndex(
            model_name='mechaniclocation',
            index=models.Index(fields=['mechanic', 'is_online'], name='mechanic_lo_mechani_4ed1aa_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['user', 'status'], name='tracking_se_user_id_bf769f_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['vehicle', 'status'], name='tracking_se_vehicle_a89f57_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['tracking_type', 'status'], name='tracking_se_trackin_2d8a97_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['last_location_at'], name='tracking_se_last_lo_a8f972_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(fields=['vehicle', 'recorded_at'], name='vehicle_loc_vehicle_fe624b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(fields=['session', 'recorded_at'], name='vehicle_loc_session_3798cd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(fields=['latitude', 'longitude'], name='vehicle_loc_latitud_8662b6_idx'),
        ),
    ]
