# Generated by Django 6.0.6 on 2026-09-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_deposit_amount_booking_deposit_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='countdown_ends_at',
            field=models.DateTimeField(blank=True, help_text='Mda countdown inaisha', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='countdown_started_at',
            field=models.DateTimeField(blank=True, help_text='Mda countdown ilianza', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Masaa ya mechanic kumfikia mteja (1-24)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Dakika za ziada (0-59)', null=True),
        ),
    ]
