# Generated by Django 6.0.6 on 2026-09-28 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_accepted_at_booking_countdown_ends_at_and_more'),
        ('services', '0007_alter_servicebooking_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.service'),
        ),
    ]
