# Generated by Django 6.0.6 on 2026-08-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('decimal', 'Decimal')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('payment', 'Payment'), ('notification', 'Notification'), ('email', 'Email'), ('security', 'Security'), ('feature', 'Feature'), ('appearance', 'Appearance'), ('integration', 'Integration')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
    ]
