# Generated by Django 6.0.6 on 2026-09-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text="Siku zinazopatikana: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']"),
        ),
        migrations.AddField(
            model_name='service',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Muda wa kumaliza (mfano: 18:00)', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='fixed_price',
            field=models.BooleanField(default=False, help_text='Kama True, bei haiwezi kubadilishwa (mfano: AI Diagnosis 30k)'),
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Muda wa kuanza (mfano: 08:00)', null=True),
        ),
    ]
