# Generated by Django 6.0.6 on 2026-09-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_available_days_service_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, help_text='Video ya service (mp4, webm, max 50MB)', null=True, upload_to='services/videos/%Y/%m/'),
        ),
    ]
