# Generated by Django 6.0.6 on 2026-09-26 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
        ('services', '0004_seed_car_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.CharField(blank=True, max_length=20)),
                ('vehicle_registration', models.CharField(blank=True, max_length=50)),
                ('vehicle_notes', models.TextField(blank=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Haijalipwa'), ('DEPOSIT_PAID', 'Deposit imelipwa'), ('FULLY_PAID', 'Imelipwa yote')], db_index=True, default='UNPAID', max_length=20)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payment_phone', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(default='MOBILE_MONEY', max_length=20)),
                ('detected_network', models.CharField(blank=True, max_length=30)),
                ('payment_countdown_ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Inasubiri malipo'), ('DEPOSIT_PAID', 'Deposit imelipwa'), ('CONFIRMED', 'Imethibitishwa na admin'), ('IN_PROGRESS', 'Inafanyika'), ('COMPLETED', 'Imekamilika'), ('CANCELLED', 'Imefutwa')], db_index=True, default='PENDING_PAYMENT', max_length=30)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.CharField(blank=True, max_length=20)),
                ('service_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('service_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('service_location', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('eta_minutes', models.PositiveIntegerField(default=0)),
                ('eta_countdown_ends_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('extended_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('user_rating', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanic_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='mechanics.mechanicprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_bookings', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
