# Generated by Django 6.0.6 on 2026-09-27 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_mechanicprofile_is_online_and_more'),
        ('services', '0005_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='assigned_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_bookings', to='mechanics.mechanicprofile'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='custom_service_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='custom_service_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='custom_service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='schedule_countdown_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='schedule_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='scheduled_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_bookings', to='services.service'),
        ),
    ]
