# Generated by Django 6.0.6 on 2026-09-27 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicebooking_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='services.service'),
        ),
    ]
