# Generated by Django 6.0.6 on 2026-08-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(db_index=True, max_length=50)),
                ('total_users', models.PositiveBigIntegerField(default=0)),
                ('total_mechanics', models.PositiveBigIntegerField(default=0)),
                ('total_vehicles', models.PositiveBigIntegerField(default=0)),
                ('total_bookings', models.PositiveBigIntegerField(default=0)),
                ('total_orders', models.PositiveBigIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dashboard_snapshots',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['snapshot_type', 'generated_at'], name='dashboard_s_snapsho_36101b_idx')],
            },
        ),
    ]
