# Generated by Django 6.0.6 on 2026-09-01 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OBDScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONNECTING', 'Connecting'), ('SCANNING', 'Scanning'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('adapter_name', models.CharField(blank=True, max_length=150)),
                ('protocol', models.CharField(blank=True, max_length=100)),
                ('dtc_codes', models.JSONField(blank=True, default=list)),
                ('live_data', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obd_scans', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obd_scans', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'obd_scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
