# Generated by Django 6.0.6 on 2026-08-10 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BluetoothDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Platform-specific Bluetooth identifier.', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('OBD_ADAPTER', 'OBD-II Adapter'), ('ELM327', 'ELM327'), ('OBDLINK', 'OBDLink'), ('GENERIC', 'Generic Bluetooth Device')], default='GENERIC', max_length=30)),
                ('connection_type', models.CharField(choices=[('CLASSIC', 'Bluetooth Classic'), ('BLE', 'Bluetooth Low Energy')], default='CLASSIC', max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
                ('hardware_version', models.CharField(blank=True, max_length=100)),
                ('protocol', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('AVAILABLE', 'Available'), ('PAIRED', 'Paired'), ('CONNECTING', 'Connecting'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], db_index=True, default='UNKNOWN', max_length=20)),
                ('is_paired', models.BooleanField(default=False)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluetooth_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bluetooth_devices',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BluetoothConnectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CONNECTING', 'Connecting'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('FAILED', 'Failed')], db_index=True, default='CREATED', max_length=20)),
                ('connection_type', models.CharField(choices=[('CLASSIC', 'Bluetooth Classic'), ('BLE', 'Bluetooth Low Energy')], max_length=20)),
                ('transport_identifier', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluetooth_connection_sessions', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_sessions', to='bluetooth.bluetoothdevice')),
            ],
            options={
                'db_table': 'bluetooth_connection_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OBDCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('REQUEST', 'Request'), ('RESPONSE', 'Response')], max_length=20)),
                ('raw_data', models.TextField(blank=True)),
                ('decoded_data', models.JSONField(blank=True, default=dict)),
                ('successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='bluetooth.bluetoothconnectionsession')),
            ],
            options={
                'db_table': 'obd_command_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OBDTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('raw_value', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='bluetooth.bluetoothconnectionsession')),
            ],
            options={
                'db_table': 'obd_telemetry',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bluetoothdevice',
            index=models.Index(fields=['user', 'status'], name='bluetooth_d_user_id_ed1f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='bluetoothdevice',
            index=models.Index(fields=['device_id'], name='bluetooth_d_device__7d63db_idx'),
        ),
        migrations.AddConstraint(
            model_name='bluetoothdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='unique_bluetooth_device_per_user'),
        ),
        migrations.AddIndex(
            model_name='bluetoothconnectionsession',
            index=models.Index(fields=['user', 'status'], name='bluetooth_c_user_id_94207b_idx'),
        ),
        migrations.AddIndex(
            model_name='bluetoothconnectionsession',
            index=models.Index(fields=['device', 'created_at'], name='bluetooth_c_device__3a3a91_idx'),
        ),
        migrations.AddIndex(
            model_name='obdcommandlog',
            index=models.Index(fields=['connection', 'created_at'], name='obd_command_connect_5bfb40_idx'),
        ),
        migrations.AddIndex(
            model_name='obdcommandlog',
            index=models.Index(fields=['command'], name='obd_command_command_cc3972_idx'),
        ),
        migrations.AddIndex(
            model_name='obdtelemetry',
            index=models.Index(fields=['connection', 'recorded_at'], name='obd_telemet_connect_f9eb06_idx'),
        ),
        migrations.AddIndex(
            model_name='obdtelemetry',
            index=models.Index(fields=['pid', 'recorded_at'], name='obd_telemet_pid_cf2ef5_idx'),
        ),
    ]
