# Generated by Django 6.0.6 on 2026-09-01 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SYMPTOMS', 'Symptoms'), ('OBD', 'OBD-II'), ('AI', 'AI Diagnosis')], default='SYMPTOMS', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('user_description', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('possible_causes', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnosis_sessions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnosis_sessions', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'ai_diagnosis_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
