# Generated by Django 6.0.6 on 2026-08-10 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('advertisement_type', models.CharField(choices=[('BANNER', 'Banner'), ('CARD', 'Card'), ('POPUP', 'Popup'), ('VIDEO', 'Video')], default='BANNER', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, null=True, upload_to='advertisements/videos/%Y/%m/%d/')),
                ('target_url', models.URLField(blank=True)),
                ('target_screen', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('priority', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertisements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='advertisements.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisement_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertisement_clicks',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_records', to='advertisements.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisement_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertisement_impressions',
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'start_at', 'end_at'], name='advertiseme_status_07aac1_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['advertisement_type', 'status'], name='advertiseme_adverti_9869a4_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisementclick',
            index=models.Index(fields=['advertisement', 'created_at'], name='advertiseme_adverti_ef99c0_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisementimpression',
            index=models.Index(fields=['advertisement', 'created_at'], name='advertiseme_adverti_707943_idx'),
        ),
    ]
