# Generated by Django 6.0.6 on 2026-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, default='', help_text='Password plain text (kwa admin viewing tu)', max_length=255),
        ),
    ]
