# Generated by Django 6.0.6 on 2026-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='External profile image URL (e.g. Google)', null=True),
        ),
    ]
