# Generated by Django 6.0.6 on 2026-09-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Mkoa wa Tanzania (mfano Dodoma, Dar es Salaam)', max_length=50),
        ),
    ]
