# Generated by Django 6.0.6 on 2026-09-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='spare_parts/images/'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
