# Generated by Django 6.0.6 on 2026-09-20 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0002_alter_sparepart_main_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_type', models.CharField(choices=[('DELIVERY', 'Delivery to Location'), ('PICKUP', 'Pickup at Garage')], default='DELIVERY', max_length=20)),
                ('delivery_location', models.CharField(blank=True, max_length=255)),
                ('delivery_region', models.CharField(blank=True, max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=20)),
                ('delivery_notes', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payment_status', models.CharField(default='UNPAID', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_PAYMENT', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='spare_parts.sparepart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spare_part_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
