# Generated by Django 6.0.6 on 2026-09-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0004_sparepartorder_delivery_countdown_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartorder',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='detected_network',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='payment_method',
            field=models.CharField(default='MOBILE_MONEY', max_length=20),
        ),
    ]
