# Generated by Django 6.0.6 on 2026-09-29 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0005_sparepartorder_bank_account_sparepartorder_bank_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('poor', 'Poor'), ('bad', 'Bad'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='spare_parts.sparepartorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_feedbacks',
            },
        ),
    ]
