# Generated by Django 6.0.6 on 2026-08-10 23:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('registration_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True)),
                ('engine_type', models.CharField(blank=True, max_length=100)),
                ('engine_capacity_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('OTHER', 'Other')], default='PETROL', max_length=20)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic'), ('AMT', 'AMT'), ('CVT', 'CVT'), ('DCT', 'DCT'), ('OTHER', 'Other')], default='MANUAL', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('mileage_km', models.PositiveBigIntegerField(blank=True, null=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicles/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='vehicles_user_id_c816b0_idx'), models.Index(fields=['make', 'model', 'year'], name='vehicles_make_f7084a_idx'), models.Index(fields=['registration_number'], name='vehicles_registr_eb8990_idx'), models.Index(fields=['vin'], name='vehicles_vin_42311c_idx')],
            },
        ),
    ]
