# Generated by Django 6.0.6 on 2026-08-16 05:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mechanics', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DTCCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('system', models.CharField(choices=[('POWERTRAIN', 'Powertrain'), ('CHASSIS', 'Chassis'), ('BODY', 'Body'), ('NETWORK', 'Network'), ('GENERIC', 'Generic')], default='GENERIC', max_length=30)),
                ('category', models.CharField(choices=[('ENGINE', 'Engine'), ('TRANSMISSION', 'Transmission'), ('EMISSIONS', 'Emissions'), ('FUEL', 'Fuel'), ('IGNITION', 'Ignition'), ('COOLING', 'Cooling'), ('BRAKE', 'Brake'), ('ELECTRICAL', 'Electrical'), ('COMMUNICATION', 'Communication'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('possible_symptoms', models.JSONField(blank=True, default=list)),
                ('possible_causes', models.JSONField(blank=True, default=list)),
                ('diagnostic_steps', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('recommended_repair', models.TextField(blank=True)),
                ('recommended_repairs', models.JSONField(blank=True, default=list)),
                ('solutions', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('is_common', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_emission_related', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OBDPID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_diagnosis_used', models.BooleanField(default=False)),
                ('free_diagnosis_date', models.DateField(blank=True, null=True)),
                ('paid_diagnosis_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_entitlement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('OBD', 'OBD-II'), ('FLUTTER', 'Flutter'), ('MECHANIC', 'Mechanic')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONNECTING', 'Connecting'), ('SCANNING', 'Scanning'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_DTC', 'Completed with DTC'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('protocol', models.CharField(blank=True, max_length=100)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('device_mac_address', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanics.mechanicprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_sessions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='OBDReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.obdpid')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='diagnosis.diagnosissession')),
            ],
        ),
        migrations.CreateModel(
            name='OBDScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='diagnosis.diagnosissession')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisDTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('HISTORICAL', 'Historical')], default='ACTIVE', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtcs', to='diagnosis.diagnosissession')),
                ('dtc_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.dtccode')),
            ],
            options={
                'unique_together': {('session', 'raw_code')},
            },
        ),
    ]
