# Generated by Django 6.0.6 on 2026-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='file_url',
            field=models.URLField(blank=True, help_text='Direct Cloudinary URL', null=True),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/attachments/'),
        ),
    ]
