# Generated by Django 6.0.6 on 2026-09-23 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_deleted_at_message_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('user_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('user_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('mechanic_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('mechanic_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('countdown_ends_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user_confirmed_arrival', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_ready_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_requests', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_ready_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
