# Generated by Django 6.0.6 on 2026-09-26 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_bookingapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineMechanicRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NOTIFIED', 'Mechanic Notified'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('user_message', models.TextField(blank=True)),
                ('user_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('user_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('mechanic_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_requests_received', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_requests', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_mechanic_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offline_mechanic_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mechanic', 'status'], name='offline_mec_mechani_a358bd_idx'), models.Index(fields=['user', 'status'], name='offline_mec_user_id_f730da_idx')],
            },
        ),
    ]
