# Generated by Django 6.0.6 on 2026-09-27 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_offlinemechanicrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readyrequest',
            name='gps_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readyrequest',
            name='gps_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readyrequest',
            name='gps_shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readyrequest',
            name='place_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='readyrequest',
            name='schedule_countdown_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readyrequest',
            name='scheduled_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readyrequest',
            name='scheduled_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readyrequest',
            name='scheduled_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readyrequest',
            name='user_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
